version: '3'
services:

  magento:
    build: docker
    container_name: jeki-app
    working_dir: /var/www/html/magento
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./web/logs:/var/log/nginx
      - ./docker/nginx:/var/www/html/conf/nginx
      - ./docker/php/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/docker-zz.ini:/usr/local/etc/php/conf.d/docker-zz.ini
    env_file:
      - .env

  # dev mysql db:
  db:
    image: mysql:5.7
    container_name: jeki-db
    working_dir: /dump
    volumes:
      - ./docker/dump:/dump
      - ./web/logs:/var/log/mysql:rw
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  db:
